name: Import Jobs to Supabase

on:
  schedule:
    - cron: "0 * * * *" # runs every hour
  workflow_dispatch: # lets you run manually

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch @supabase/supabase-js

      - name: Run import script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node importJobs.js
